### PR TITLE
add dkms functionality

### PR DESCRIPTION
**Pull request by leifliddy**
add dkms functionality

`./install.cirrus.driver.sh` compiles and installs the module like it normally does

`./install.cirrus.driver.sh -i` installs the dkms config -- this will build the module for the current kernel -- and whenever a new kernel is installed -- it'll auto-build a module for that kernel

`./install.cirrus.driver.sh -r`  removes the dkms config

It wasn't possible to have a single unified script. If you try to run the `dkms install` command from `install.cirrus.driver.sh` script....then dkms will then call the same script -- so you run into this recursive situation where the `install.cirrus.driver.sh` is being called a 2nd time before its exited from the initial run -- and it just loops over itself. Therefore I've moved the dkms install/remove functionality to `dkms.sh` which I purposefully made non-executable -- as only `install.cirrus.driver.sh` is meant to call it.

There's several things I had to do to get things to work properly -- like using the `cur_dir` variable (in `./install.cirrus.driver.sh`) which I needed to use to get this to work with dkms. I'm not sure why, I didn't need to use that in the script for my project. I'll take a closer look at that later though. 

If you have any questions -- please let me know. 

One more thing.....
https://manpages.ubuntu.com/manpages/kinetic/man8/dkms.8.html
```
     KERNELRELEASE will be automatically appended to MAKE[#]. If you  want  to  suppress
              this behavior, you can quote the make command: 'make'.
```

That's the reason I changed `KVER` to `KERNELRELEASE`

### CODE REVIEW

**Review by davidjo — APPROVED** [review]

**Comment by leifliddy** [comment]
That last commit you made might need to be reworked a bit.
```
    update_dir="/lib/modules/${UNAME}/updates"
    echo -e "\ncontents of $update_dir/dkms"
    ls -lA $update_dir/dkms
```
On my Fedora system  -- even though dkms will ignore the value of DEST_MODULE_LOCATION[0] -- it will _always_ install the module to `/lib/modules/{UNAME}/extra` and not to `updates`

In anycase the output the `dkms.sh` will show you the directory where it's installing the module to. Perhaps there a dksm cmd you can run to show you where the

**Comment by davidjo** [comment]
Well great - on Ubuntu its definitely going to updates/dkms (this is true for eg the nvidia GPU proprietary driver).

**Comment by leifliddy** [comment]
Yup, my nvidia modules are being installed to the same location
```/usr/lib/modules/6.5.8-200.fc38.x86_64/extra/nvidia/nvidia-modeset.ko.xz
/usr/lib/modules/6.5.8-200.fc38.x86_64/extra/nvidia/nvidia-peermem.ko.xz
/usr/lib/modules/6.5.8-200.fc38.x86_64/extra/nvidia/nvidia-uvm.ko.xz
/usr/lib/modules/6.5.8-200.fc38.x86_64/extra/nvidia/nvidia.ko.xz
```

This is a pretty trivial thing to be honest. If I'm bored this weekend -- I can sort something out

**Comment by davidjo** [comment]
Well Im guessing it looks as all those distributions that ignore DEST_MODULE_LOCATION could have their own idea of where to put the modules.
Just checked it looks as though the extra directory in Fedora is similar to the updates in Ubuntu in that modules in extra override existing modules - so dkms can just remove from extra and the original module is reactivated.
Guess we can just handle the 2 we know about.

**Pull request merged**
